services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=interview'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=interview'
    ports:
      - '5432:5432'
  app:
    build: .
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/interview'
      - 'SPRING_DATASOURCE_USERNAME=interview'
      - 'SPRING_DATASOURCE_PASSWORD=password'
    ports:
      - '8080:8080'
    depends_on:
      - postgres

